spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/mind_mate?createDatabaseIfNotExist=true
    username: root
    password: Batman
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 604800 #900 # 15mins #300 # 5min
    refreshTokenExpiration: 604800 # 7 days